### ISSUE TITLE
Crash when Rotating L-Shaped Tetromino near Right Edge

### ISSUE THREAD

**Issue by romandykyi** [ILLIAK31/Tetris#1]
I encountered a bug while playing the Tetris game. Whenever I attempt to rotate the L-shaped tetromino(either orange or blue one) near the right edge of the game grid, the application crashes. This issue consistently occurs and is reproducible using the following steps:

1. Launch the game.
2. Move an L-shaped tetromino towards the right edge of the grid.
3. Attempt to rotate the tetromino by pressing the up arrow.

Upon performing these steps, the game crashes with the following error:
![Bug2](https://github.com/ILLIAK31/Tetris/assets/94003504/fc315c5b-72ca-46d6-8ac6-30516fb93357)

Call stack:
```
        Tetris.exe!std::vector<std::vector<unsigned char,std::allocator<unsigned char>>,std::allocator<std::vector<unsigned char,std::allocator<unsigned char>>>>::operator[](const unsigned __int64 _Pos) Line 1883	C++
>	Tetris.exe!Game::check_collision(int type) Line 1583	C++
 	Tetris.exe!Game::Process() Line 361	C++
 	Tetris.exe!Game::Run() Line 129	C++
 	Tetris.exe!main() Line 8	C++
 	[External Code]	
```

**Comment by ILLIAK31** [comment]
Thanks for the found error and the comment. The collision issue has been resolved  :)

**Comment by romandykyi** [comment]
The issue has been resolved. Good job!
